vm:
  ram: 16
  cpucores: 4
  cpusockets: 1
  description: "OpenShift MiniShift"
  template: "template_centos_7"

ovirt:
  manager: ovirt-mng.it-linux.priv
  datacenter: IT-Linux
  cluster: IT-Linux
  node: ovirt-01.it-linux.priv
  # Type ovirtmgmt for admin network or let it empty for dmz
  switch_admin: ovirtmgmt
   # Type dmzmgmt for dmz network or let it empty for admin
  switch_dmz:
  ha: false
  disk:
    data1:
      taille: 40
      format: cow
      datastore: datastore_vm_01
      interface: virtio_scsi
      name: "{{ inventory_hostname }}_root"
      mount: /root
    # data2:
    #   taille: 4
    #   format: cow
    #   datastore: datastore_vm_01
    #   interface: virtio_scsi
    #   name: "{{ inventory_hostname }}_swap"
    #   mount: /swap
    data3:
      taille: 100
      format: cow
      datastore: datastore_vm_01
      interface: virtio_scsi
      name: "{{ inventory_hostname }}_applis"
      mount: /applis

reseau:
  dns1: 192.168.10.103
  dns2: 192.168.10.104
  domain: it-linux.priv
  ipa_server: "lx0001.it-linux.priv"

katello:
  user: "{{ katello_user }}"
  pass: "{{ katello_pass }}"
  server: lx0000.it-linux.priv
  ak: AK_PRO_C_7
  org: IT-LINUX
  hg: HG_PRO_C_7
  location: NIORT
  rpm_ca: katello-ca-consumer-latest.noarch.rpm 
